project:
  type: website

website:
  title: "OJALAB"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: news.qmd
        text: News
      - href: opportunities.qmd
        text: Opportunities
      - href: people.qmd
        text: People
      - href: publications.qmd
        text: Publications

    right:
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: flatly
    css: styles.css
    toc: true


